version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  publisher:
    build:
      context: ./publisher
    volumes:
      - ./publisher:/app
      - /app/node_modules
    depends_on:
      - mqtt-broker
  shared-subscriber:
    build:
      context: ./subscriber
    deploy:
      replicas: 3
    environment:
      - MQTT_GROUP_ID=shared-subscriber-group
    volumes:
      - ./subscriber:/app
      - /app/node_modules
    depends_on:
      - mqtt-broker
  anonymous-subscriber: # this subscriber will not be part of the group
    build:
      context: ./subscriber
    deploy:
      replicas: 2
    volumes:
      - ./subscriber:/app
      - /app/node_modules
    depends_on:
      - mqtt-broker
